### PR TITLE
Added realtime lux sensor

### PR DESCRIPTION
**Pull request by OultonD**
I added a service to do realtime polling of a lux sensor

### CODE REVIEW

**Comment by NovaGL** [comment]
What is a lux sensor? If it is a specific brand maybe it should go in its own repo.

Otherwise can you give me an explanation of what your changes do. We would also need to update readme if I am to merge this.

**Comment by OultonD** [comment]
A lux sensor senses ambient light. I read my data from a photocell connected to an ESP8266, but it could be anything that senses ambient light.

Edit: Essentially I have added a couple of new types of generic sensors that this plugin can support

**Comment by NovaGL** [comment]
Update the readme for how these new devices should be used I'll review and let you know

**Comment by OultonD** [comment]
I added a table to the bottom of the readme. It could be updated with the original supported sensors as well.

**Pull request merged**
